{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aspects",
    "version": "6.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.1.1.jar",
          "url": "spring-aspects-6.1.1.jar",
          "size": 49825,
          "sha512": "d1d49eb65381ad594badd9625ec5e0a9fd4cf46812ba0ecea9dcd4f1f0398d3b690fb822ff3f94282c3b412cbe57d96de48620ec5a0fcb6300ec82e819d510af",
          "sha256": "95420b1f058aa3121ad0da1e1d58686d46230facae66a25566f2f127e829d06a",
          "sha1": "bfcb6682e205b4ef6ae7986ac7ea35eae29f31f4",
          "md5": "f01cddf77784ee7df0e9abbbd69989a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aspects-6.1.1.jar",
          "url": "spring-aspects-6.1.1.jar",
          "size": 49825,
          "sha512": "d1d49eb65381ad594badd9625ec5e0a9fd4cf46812ba0ecea9dcd4f1f0398d3b690fb822ff3f94282c3b412cbe57d96de48620ec5a0fcb6300ec82e819d510af",
          "sha256": "95420b1f058aa3121ad0da1e1d58686d46230facae66a25566f2f127e829d06a",
          "sha1": "bfcb6682e205b4ef6ae7986ac7ea35eae29f31f4",
          "md5": "f01cddf77784ee7df0e9abbbd69989a7"
        }
      ]
    }
  ]
}
