{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter",
    "version": "5.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-5.9.1.jar",
          "url": "junit-jupiter-5.9.1.jar",
          "size": 6358,
          "sha512": "2c0cae840e61ec33f98480ba2b5603eeac9d53dccb39441d4b3aee1c8baa5c75b3110f0d3f6334c2f7a06870fabd9710543deb441179e23091b5fa09d7449c5e",
          "sha256": "e305ce7b01adfcc89b4eee03bca473eeb68925a596d8ccca404a436344fc1965",
          "sha1": "9274d3757e224bc02eae367bd481062a263c150b",
          "md5": "f9e29d72f8e9dc363e63b77600fc430a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-5.9.1.jar",
          "url": "junit-jupiter-5.9.1.jar",
          "size": 6358,
          "sha512": "2c0cae840e61ec33f98480ba2b5603eeac9d53dccb39441d4b3aee1c8baa5c75b3110f0d3f6334c2f7a06870fabd9710543deb441179e23091b5fa09d7449c5e",
          "sha256": "e305ce7b01adfcc89b4eee03bca473eeb68925a596d8ccca404a436344fc1965",
          "sha1": "9274d3757e224bc02eae367bd481062a263c150b",
          "md5": "f9e29d72f8e9dc363e63b77600fc430a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-5.9.1-javadoc.jar",
          "url": "junit-jupiter-5.9.1-javadoc.jar",
          "size": 5681,
          "sha512": "1fae01f45210a2a2a4f67b91eddda48f1d238140a97c49ec9f0d7311679ad4af48265273e5efcefa2f311ccf2e0653ccc76af9050f0807a8fded566d99178fea",
          "sha256": "87e2e56e44d1ce3a882eff2bed179ea74a27cbcbd888f13536c413a87d32f58a",
          "sha1": "3c791495768512669e0463f7be775c1ee4ea10c3",
          "md5": "6c7369516c034cf85e6adbce4a9ed291"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-5.9.1-sources.jar",
          "url": "junit-jupiter-5.9.1-sources.jar",
          "size": 6092,
          "sha512": "261e62db845b133ee533676255e3d4961911cd97dba8962e90b580d6fc87b4c813956d50d688341a4e603d3463db0f340e9c440b573222b98a80350821029cd6",
          "sha256": "2d0cfc6150ce624fe19b039a483ef0a0ba54620916282b0e35ea78f7626abb50",
          "sha1": "5fd01c33132462aab3905cb74bd1097a713ab91a",
          "md5": "fb39489b11df433439ec53e5bf32ee12"
        }
      ]
    }
  ]
}
